# Site settings
title: Your Website Title
description: Your website description
baseurl: "/PaintBot" # Set this if your site is hosted in a subdirectory
url: "https://minaamakary.github.io" # Set your website URL

# Theme settings
theme: jekyll-theme-minimal # Choose a Jekyll theme

# Navigation links
nav:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Blog
    url: /blog

# Social media links
social:
  - title: GitHub
    url: https://github.com/your-username
  - title: Twitter
    url: https://twitter.com/your-username

# Build settings
plugins:
  - jekyll-feed # Add more plugins if needed

# Additional settings
# Add any additional settings or customization specific to your website here